server:
  port: ${SERVER_PORT:8005}

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/intraOralBill/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/intraOralBill/api-docs/swagger-ui.html

spring:
  application:
    name: ${SERVICE_NAME:IntraOralBillService}
  profiles:
    active: ${ACTIVE_PROFILE:desktop-dev} #nitro-dev or desktop-prod or macc-prod or nitro-kub-prod
  cloud:
    function:
      definition: intraOralTreatmentPlanConsumerFunction
    stream:
      bindings:
        intraOralTreatmentPlanConsumerFunction-in-0:
          destination: IntraoralBill-sent
          group: ${SERVICE_NAME:spring.application.name}-group
        sendIntraoralBillService-out-0:
          destination: send-IntraoralBill
      kafka:
        binder:
          brokers: ${DB_HOST:https://localhost}:9092

item:
  request:
    api:
      intraoralExaminationGetList: /api/v1/intraoral/{profileId}

resilience4j:
  circuitbreaker:
    instances:
      externalIntraoralExamination:
        event-consumer-buffer-size: 10
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED